# Generated by Django 5.2.15 on 2026-06-09 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelvendor',
            name='business_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
