# Generated by Django 5.2.15 on 2026-06-08 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hoteluser',
            name='phone_number',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
