# Generated by Django 5.2.15 on 2026-06-08 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_hoteluser_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='ameneties',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='hotel_owner',
        ),
        migrations.RemoveField(
            model_name='hotelmanager',
            name='hotel',
        ),
        migrations.RemoveField(
            model_name='hotelimage',
            name='hotel',
        ),
        migrations.RemoveField(
            model_name='hoteluser',
            name='user_ptr',
        ),
        migrations.RemoveField(
            model_name='hotelvendor',
            name='user_ptr',
        ),
        migrations.DeleteModel(
            name='Ameneties',
        ),
        migrations.DeleteModel(
            name='HotelManager',
        ),
        migrations.DeleteModel(
            name='Hotel',
        ),
        migrations.DeleteModel(
            name='HotelImage',
        ),
        migrations.DeleteModel(
            name='HotelUser',
        ),
        migrations.DeleteModel(
            name='HotelVendor',
        ),
    ]
